#ifndef ESTADOS_H
#define ESTADOS_H

// ESTADO DE GRAVEDAD DEL PACIENTE
typedef enum 
{
    GRAVEDAD_LEVE = 0,
    GRAVEDAD_MODERADA = 1,
    GRAVEDAD_GRAVE = 2
} GravedadPaciente;

// ESTADOS DE LA UNIDAD
typedef enum 
{
    UNIDAD_OCUPADA = 0,
    UNIDAD_DISPONIBLE = 1,
    UNIDAD_DESCANSANDO = 2
} EstadoUnidad;

// ESTADOS DE LA LLAMADA
typedef enum 
{
    LLAMADA_PENDIENTE = 0,
    LLAMADA_EN_ATENCION = 1,
    LLAMADA_FINALIZADA = 2
} EstadoLlamada;

// ESTADO DE INCIDENTE
typedef enum 
{
    INCIDENTE_EN_CAMINO = 0,
    INCIDENTE_EN_LUGAR = 1,
    INCIDENTE_TRASLADO = 2,
    INCIDENTE_CERRADO = 3
} EstadoIncidente;

// ESTADOS DEL TURNO
typedef enum
{
    TURNO_ACTIVO = 0,
    TURNO_DESCANSO = 1,
    TURNO_FUERA_SERVICIO = 2
} EstadoTurno;

// ESTADOS DEL DETENIDO
typedef enum 
{
    DETENIDO_EN_CUSTODIA = 0,
    DETENIDO_TRASLADADO = 1,
    DETENIDO_LIBERADO = 2
} EstadoDetenido;

// ESTADO DEL PACIENTE
typedef enum
{
    PACIENTE_ESPERANDO = 0,
    PACIENTE_EN_RUTA = 1,
    PACIENTE_EN_HOSPITAL = 2
} EstadoPaciente;

#endif
